# Generated by Django 3.1.4 on 2020-12-15 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AuthRESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometricToken',
            field=models.CharField(default='xxx', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='biometricTokenExp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='biometricTokenIAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
