# Generated by Django 3.1.4 on 2020-12-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthRESTAPI', '0003_auto_20201220_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometricToken',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='publicKey',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
