# Generated by Django 3.1.4 on 2020-12-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthRESTAPI', '0004_auto_20201227_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='biometricToken',
            new_name='biometric_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='publicKey',
            new_name='public_key',
        ),
    ]
