# Generated by Django 3.1.4 on 2020-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthRESTAPI', '0006_auto_20201228_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biometricToken',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='publicKey',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
