# Generated by Django 3.1.4 on 2021-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthRESTAPI', '0007_auto_20201228_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biometricToken',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='publicKey',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
